apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: tracing-istioinaction
  namespace: istioinaction
spec:
  tracing:
  - providers:
      - name: zipkinlocal
    disableSpanReporting: false
    randomSamplingPercentage: 100

